// extension -> vscode-icons key
window.EXT_TO_ICONKEY = {
  // ---- Code ----
  js: "js",
  mjs: "js",
  cjs: "js",
  jsx: "reactjs",
  ts: "typescript",
  mts: "typescript",
  cts: "typescript",
  tsx: "reactts",
  java: "java",
  cs: "csharp",
  json: "json",
  jsonc: "json",
  json5: "json",
  md: "markdown",
  mdx: "mdx",
  html: "html",
  htm: "html",
  css: "css",
  scss: "sass",
  sass: "sass",
  less: "less",
  py: "python",
  pyc: "python",
  go: "go",
  rs: "rust",
  php: "php",
  rb: "ruby",
  c: "c",
  cpp: "cpp",
  cc: "cpp",
  cxx: "cpp",
  h: "h",
  hpp: "hpp",
  hxx: "hpp",
  swift: "swift",
  kt: "kotlin",
  kts: "kotlin",
  dart: "dart",
  r: "r",
  lua: "lua",
  perl: "perl",
  pl: "perl",
  scala: "scala",
  clj: "clojure",
  ex: "elixir",
  exs: "elixir",
  vue: "vue",
  svelte: "svelte",
  astro: "astro",
  elm: "elm",
  yml: "yaml",
  yaml: "yaml",
  xml: "xml",
  sql: "sql",
  sh: "shell",
  bash: "shell",
  zsh: "shell",
  fish: "shell",
  bat: "bat",
  cmd: "bat",
  ps1: "powershell",
  psm1: "powershell",

  // ---- .NET / Visual Studio ----
  xaml: "xaml",
  sln: "sln",
  csproj: "csproj",
  vbproj: "vbproj",
  fsproj: "fsproj",
  "csproj.user": "csproj",
  vb: "vb",
  fs: "fsharp",
  fsx: "fsharp",
  resx: "resx",

  // ---- Web / Frontend ----
  wasm: "wasm",
  graphql: "graphql",
  gql: "graphql",
  prisma: "prisma",

  // ---- Build / Config ----
  gradle: "gradle",
  dockerfile: "docker",
  dockerignore: "docker",
  makefile: "makefile",
  cmake: "cmake",
  gitignore: "git",
  gitattributes: "git",
  gitmodules: "git",
  npmrc: "npm",
  nvmrc: "node",
  editorconfig: "editorconfig",
  eslintrc: "eslint",
  prettierrc: "prettier",
  babelrc: "babel",
  webpack: "webpack",
  vite: "vite",
  tsconfig: "tsconfig",

  // ---- Package Managers ----
  lock: "lock",

  // ---- Data ----
  csv: "csv",
  tsv: "csv",
  parquet: "database",
  db: "database",
  sqlite: "database",
  sqlite3: "database",

  // ---- Media (additional) ----
  mp3: "audio",
  wav: "audio",
  flac: "audio",
  ogg: "audio",
  aac: "audio",
  m4a: "audio",
  wma: "audio",

  mp4: "video",
  mkv: "video",
  avi: "video",
  mov: "video",
  webm: "video",
  flv: "video",
  wmv: "video",

  png: "image",
  jpg: "image",
  jpeg: "image",
  gif: "image",
  webp: "image",
  svg: "svg",
  ico: "image",
  bmp: "image",
  tiff: "image",
  tif: "image",
  heic: "image",
  avif: "image",

  // ---- Documents ----
  pdf: "pdf",
  doc: "word",
  docx: "word",
  odt: "word",
  rtf: "document",
  ppt: "powerpoint",
  pptx: "powerpoint",
  odp: "powerpoint",
  xls: "excel",
  xlsx: "excel",
  ods: "excel",
  txt: "file",
  log: "log",

  // ---- Archives ----
  zip: "zip",
  rar: "zip",
  "7z": "zip",
  tar: "zip",
  gz: "zip",
  bz2: "zip",
  xz: "zip",
  tgz: "zip",

  // ---- Fonts ----
  ttf: "font",
  otf: "font",
  woff: "font",
  woff2: "font",
  eot: "font",

  // ---- Config / misc ----
  env: "settings",
  ini: "settings",
  cfg: "settings",
  toml: "settings",
  properties: "settings",
  conf: "settings",

  // ---- Certificates / Security ----
  pem: "certificate",
  crt: "certificate",
  cer: "certificate",
  key: "key",
  pub: "key",

  // ---- Markup / Templates ----
  tex: "tex",
  latex: "tex",
  hbs: "handlebars",
  mustache: "mustache",
  ejs: "ejs",
  pug: "pug",
  jade: "pug",

  // ---- Binaries ----
  exe: "binary",
  dll: "binary",
  so: "binary",
  dylib: "binary",
  app: "binary",
  apk: "android",
  ipa: "apple",
  deb: "debian",
  rpm: "rpm",
};
